### ISSUE TITLE
Using animations in callbacks causes animations to repeat

### ISSUE THREAD

**Issue by Saeven** [craigmdennis/animateCSS#24]
You can see a pen evidencing the behavior here:

https://codepen.io/Saeven/pen/OxgPzZ

Apologize if I am doing something wrong, seems like I'm following the guidelines though!

**Comment by craigmdennis** [comment]
Yeah, looks like it's a side effect of having one animation nested within another and having the event propagate up. There is an open PR addressing this problem so I will go ahead and merge that to fix this.
